### ISSUE TITLE
Plotting fails to start when plotting to an NTFS Mountpoint via SMB share.

### ISSUE THREAD

**Issue by kiwihaitch** [Chia-Network/chiapos#114]
Plotting fails to start when plotting to an NTFS Mountpoint via SMB share.

Remote Windows box:
MP            (NTFS Mount point and SMB share)
   + Subdir    (Subdirectory of MP )
   + MP2       (Subdirectory and also a NTFS Mountpoint)

Plotter:
SMB share to \\\\x.x.x.x\\MP

From both Windows and Linux plotting using the root of the share fails:

```Starting plotting progress into temporary dirs: /home/haitch/temp2 and /home/haitch/temp2
ID: c515b361ca2b44977b97dd343930c2cde19c1d672bfbcd3208769298b830e093
Plot size is: 32
Buffer size is: 4508MiB
Using 128 buckets
Using 1 threads of stripe size 65536
Caught plotting error: Could not open /home/haitch/temp2/plot-k32-2020-11-01-08-58-c515b361ca2b44977b97dd343930c2cde19c1d672bfbcd3208769298b830e093.plot.sort.tmp: Permission denied
Traceback (most recent call last):
  File "/home/haitch/chia-blockchain/venv/bin/chia", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia')())
  File "/home/haitch/chia-blockchain/src/cmds/chia.py", line 59, in main
    return chia(args, parser)
  File "/home/haitch/chia-blockchain/src/cmds/chia.py", line 53, in chia
    return args.function(args, parser)
  File "/home/haitch/chia-blockchain/src/cmds/plots.py", line 146, in handler
    create_plots(args, root_path)
  File "/home/haitch/chia-blockchain/src/plotting/create_plots.py", line 137, in create_plots
    plotter.create_plot_disk(
RuntimeError: std::exception
```

On both Windows and Linux, plotting to \\\\x.x.x.x\\MP\\Subdir does not throw an error.

On Linux, plotting to \\\\x.x.x.x\\MP\\MP2 does not throw an error.

On Windows only - plotting to \\\\x.x.x.x\\MP\\MP2, plotting again fails.

```Starting plotting progress into temporary dirs: z:\chia11 and z:\chia11
ID: 0c4af82786302bfe833e138e1e70938d394bdb2a33af13eef3034d99b7639f7f
Plot size is: 33
Buffer size is: 4600MiB
Using 128 buckets
Using 1 threads of stripe size 65536
Caught plotting error: Temp directory z:\chia11 does not exist
Traceback (most recent call last):
  File "src\cmds\chia.py", line 63, in <module>
  File "src\cmds\chia.py", line 59, in main
  File "src\cmds\chia.py", line 53, in chia
  File "src\cmds\plots.py", line 146, in handler
  File "src\plotting\create_plots.py", line 148, in create_plots
RuntimeError: Unknown exception
[6896] Failed to execute script chia
```

**Comment by hoffmang9** [comment]
Sent @kiwihaitch a test build

**Comment by hoffmang9** [comment]
Closing as fixed for the next release
