### ISSUE TITLE
BUG: Build Fails - gmake errors + subprocess.CalledProcessError exit status 2

### ISSUE THREAD

**Issue by Chewbakka-Wakka** [Chia-Network/chiapos#254]
[ 48%] Building C object CMakeFiles/RunTests.dir/src/b3/blake3_dispatch.c.o
gmake[2]: *** [CMakeFiles/RunTests.dir/build.make:76: CMakeFiles/RunTests.dir/tests/test-main.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
[ 51%] Building C object CMakeFiles/ProofOfSpace.dir/src/chacha8.c.o
...
[ 83%] Building ASM object CMakeFiles/chiapos.dir/src/b3/blake3_sse41_x86-64_unix.S.o
[ 86%] Linking CXX executable options_test
[ 86%] Built target options_test
gmake[1]: *** [CMakeFiles/Makefile2:179: CMakeFiles/RunTests.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[ 88%] Linking CXX shared module ../lib.linux-x86_64-3.8/chiapos.cpython-38-x86_64-linux-gnu.so
[ 90%] Linking CXX executable ProofOfSpace
[ 90%] Built target ProofOfSpace
[ 90%] Built target chiapos
gmake: *** [Makefile:146: all] Error 2
Traceback (most recent call last):
  File "setup.py", line 203, in <module>
    setup(
  File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib64/python3.8/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib64/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 38, in run
    self.build_extension(ext)
  File "setup.py", line 70, in build_extension
    subprocess.check_call(
  File "/usr/lib64/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j', '6']' returned non-zero exit status 2.

$ rpm -q make cmake automake
make-4.3-6.fc35.x86_64
cmake-3.20.2-2.fc35.x86_64
automake-1.16.3-5.fc35.noarch

**Comment by emlowe** [comment]
Closing issue
